Repository Akarsh-B/Identifying-the-Right-Episode-of-Care, pull requests merged in 2020-11, with the labels that each got.

#7 Cluster graph
  data/graphFile.json
  data/sourceDetails.json
  debug.log
  index.html
  scripts/graphVisualization.js
  scripts/sunBurst.js
  styles/visualization.css
Labels: feature

#11 Sun burst
  .prettierrc
  README.md
  data/graphFile.json
  data/sourceDetails.json
  debug.log
  index.html
  schedule_akarsh.txt
  schedule_sneha.txt
  schedule_suhan.docx
  scripts/graphVisualization.js
  scripts/sunBurst.js
  scripts/visualization.js
  styles/visualization.css
Labels: enhancement, feature

#13 Patient graph
  data/patients.json
  index.html
  scripts/graphVisualization.js
  scripts/patientGraph.js
  scripts/visualization.js
  styles/visualization.css
Labels: enhancement, feature

#14 Feature/cluster main
  data/cluster_membership.json
  data/edges_data.json
  data/edges_data_new.json
  data/temp.json
  index.html
  scripts/clusterGraph.js
  scripts/patientGraph.js
  scripts/sunBurst.js
  scripts/visualization.js
  styles/clusterStyles.css
  styles/visualization.css
Labels: enhancement, feature

#15 Fixed tooltip to show data for targets
  scripts/sunBurst.js
  styles/visualization.css
Labels: bug

#16 Feature/cluster main
  data/edges_data.json
  index.html
  scripts/clusterGraph.js
Labels: enhancement, feature

#25 Enhancement/sun burst
  assets/favicon.ico
  assets/risk-high.svg
  assets/risk-low.svg
  assets/risk-mod.svg
  data/temp.json
  index.html
  scripts/clusterGraph.js
  scripts/sunBurst.js
  scripts/visualization.js
  styles/sunBurstStyles.css
  styles/visualization.css
Labels: bug, enhancement
